---
# Playbook to ensure host is proxying request to the internet

#we're choosing the last public node
- name: set proxy host index in public_nodes group
  set_fact:
    proxy_public_nodes_idx: "{{ ( ( groups[ 'public_nodes' ]  | length ) - 1 ) }}"

- name: set proxy host
  set_fact:
    proxy_host:             "{{ groups[ 'public_nodes' ][ proxy_public_nodes_idx | int ] }}"

- name: set proxy host public IP
  set_fact:
    proxy_host_publicip:    "{{ hostvars[ proxy_host ].publicIPv4 }}"

- name: set proxy host private IP
  set_fact:
    proxy_host_privateip:   "{{ hostvars[ proxy_host ].privateIPv4 }}"

- name: Update apt repo
  become:                   yes
  apt:                      update_cache=yes
  register:                 apt_result
  until:                    apt_result|success
  retries:                  3
  delay:                    30
  ignore_errors:            yes
  when:                     inventory_hostname == proxy_host

- name: retry if needed using command apt-get update
  become:                   yes
  command:                  apt-get update
  when:                     inventory_hostname == proxy_host and apt_result|failed

- name: install Squid
  become:                   yes
  apt:                      pkg=squid state=installed
  register:                 apt_result
  until:                    apt_result|success
  retries:                  3
  delay:                    30
  ignore_errors:            yes
  when:                     inventory_hostname == proxy_host

- name: check Squid configuration file
  become:                   yes
  template:
    src:                    squid.conf.j2
    dest:                   /etc/squid/squid.conf
    owner:                  root
    group:                  root
    mode:                   0644
  when:                     inventory_hostname == proxy_host
  notify:
    - restart squid

- name: ensure Squid service is started and enabled on boot
  become:                   yes
  service:
    name:                   squid
    state:                  started
    enabled:                yes
  when:                     inventory_hostname == proxy_host

- name: enforce private node to use proxy for apt operations
  become:                   yes
  blockinfile:
    create:                 yes
    state:                  present
    dest:                   /etc/apt/apt.conf
    insertafter:            EOF
    block:  |
                            Acquire::http::Proxy "http://{{ proxy_host_privateip }}:{{ proxy_http_port }}";
                            Acquire::https::Proxy "https://{{ proxy_host_privateip }}:{{ proxy_http_port }}";
  when:                     inventory_hostname in groups[ 'private_nodes' ]
